import { useState, useCallback } from 'react';
import { UploadCloud, FileJson, CheckCircle } from 'lucide-react';
import { useActivities } from '../context/ActivitiesContext';
import { useNavigate } from 'react-router-dom';

export default function Workspace() {
  const [isDragging, setIsDragging] = useState(false);
  const [successMessage, setSuccessMessage] = useState('');
  const { updateActivityData } = useActivities();
  const navigate = useNavigate();

  const handleDrag = useCallback((e) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === 'dragenter' || e.type === 'dragover') {
      setIsDragging(true);
    } else if (e.type === 'dragleave') {
      setIsDragging(false);
    }
  }, []);

  const handleDrop = useCallback((e) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);

    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      processFile(file);
    }
  }, []);

  const handleChange = (e) => {
    e.preventDefault();
    if (e.target.files && e.target.files[0]) {
      processFile(e.target.files[0]);
    }
  };

  const processFile = (file) => {
    if (file.type !== 'application/json' && !file.name.endsWith('.json')) {
      alert('Please upload a valid JSON activity file.');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const json = JSON.parse(e.target.result);
        if (json.veupActivityExport && json.activityId && json.data) {
          updateActivityData(json.activityId, json.data);
          setSuccessMessage(`Successfully restored data for: ${json.activityName || json.activityId}`);
          
          // Clear message after 5 seconds
          setTimeout(() => {
            setSuccessMessage('');
          }, 5000);
        } else {
          alert('Invalid file format. Please upload a file generated by the VeUP Platform.');
        }
      } catch (err) {
        alert('Failed to parse file. Ensure it is a valid JSON document.');
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="dashboard">
      <div className="dashboard-header" style={{ marginBottom: '2rem' }}>
        <h1>My Workspace</h1>
        <p className="dashboard-subtitle">Drag and drop your previously downloaded activity files to restore your progress.</p>
      </div>

      {successMessage && (
        <div style={{ 
          backgroundColor: 'rgba(63, 185, 80, 0.1)', 
          border: '1px solid #3fb950', 
          color: '#3fb950', 
          padding: '1rem', 
          borderRadius: '8px', 
          marginBottom: '2rem',
          display: 'flex',
          alignItems: 'center',
          gap: '10px'
        }}>
          <CheckCircle size={20} />
          <span>{successMessage}</span>
          <button 
            onClick={() => navigate('/activities')} 
            style={{ 
              marginLeft: 'auto', 
              backgroundColor: '#3fb950', 
              color: '#000', 
              border: 'none', 
              padding: '6px 12px', 
              borderRadius: '4px', 
              cursor: 'pointer',
              fontWeight: 'bold'
            }}
          >
            Go to Activities
          </button>
        </div>
      )}

      <div 
        onDragEnter={handleDrag}
        onDragLeave={handleDrag}
        onDragOver={handleDrag}
        onDrop={handleDrop}
        style={{
          border: `2px dashed ${isDragging ? 'var(--primary-color)' : 'var(--border-color)'}`,
          backgroundColor: isDragging ? 'rgba(215, 255, 0, 0.05)' : 'var(--sidebar-bg)',
          borderRadius: '12px',
          padding: '4rem 2rem',
          textAlign: 'center',
          transition: 'all 0.2s ease',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: 'pointer'
        }}
        onClick={() => document.getElementById('file-upload').click()}
      >
        <input 
          type="file" 
          id="file-upload" 
          accept=".json" 
          style={{ display: 'none' }} 
          onChange={handleChange}
        />
        <div style={{ 
          backgroundColor: 'var(--card-bg)', 
          padding: '1.5rem', 
          borderRadius: '50%', 
          marginBottom: '1.5rem',
          boxShadow: '0 4px 12px rgba(0,0,0,0.2)'
        }}>
          <UploadCloud size={48} color={isDragging ? 'var(--primary-color)' : 'var(--text-muted)'} />
        </div>
        <h3 style={{ color: '#fff', fontSize: '1.5rem', marginBottom: '0.5rem' }}>
          {isDragging ? 'Drop your file here' : 'Click or drag a file to this area'}
        </h3>
        <p style={{ color: 'var(--text-muted)', maxWidth: '400px', lineHeight: '1.5' }}>
          Restore your progress by uploading a <strong>.json</strong> file generated by the "Download Hard Copy" feature.
        </p>
        
        <div style={{ marginTop: '2rem', display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-muted)', fontSize: '0.9rem' }}>
          <FileJson size={16} />
          <span>Supports VeUP Activity JSON files only</span>
        </div>
      </div>
    </div>
  );
}
